### ISSUE TITLE
What is the license for this code?

### ISSUE THREAD

**Issue by joelsherrill** [tomx4096/baremetal-lwip#1]
I am from RTEMS and was looking for LWIP drivers that work with Qemu to help improve our testing of LWIP on RTEMS. I didn't see a license in any of the files I poked at. For use with RTEMS, we need a permissive license like BSD-2 or MIT.

Could you please put a license on this code?

**Comment by tomx4096** [comment]
Hi Joel. BSD-2 license added. Best of luck
